### ISSUE TITLE
`CROSS_REMOTE=1` with persistent volume doesn't change project files

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1016]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Using `CROSS_REMOTE=1` with persistent volume, changing files in the project does not carry over across the first remote build.

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

8d8d84b

### Example

```
$ cross-util volumes create
$ cargo new --bin issue1016
$ cd issue1016
$ CROSS_REMOTE=1 cross run
...
   Compiling issue1008 v0.1.0 (/cross/Users/emil/workspace/issue1016)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `/linux-runner x86_64 target/x86_64-unknown-linux-gnu/debug/issue1016`
Hello, world!
$ # edit src/main.rs to say something else
$ CROSS_REMOTE=1 cross run
...
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `/linux-runner x86_64 target/x86_64-unknown-linux-gnu/debug/issue1016`
Hello, world!
```

### Additional information / notes

tested in ci in https://github.com/cross-rs/cross/runs/8285127194?check_suite_focus=true

**Comment by Alexhuszagh** [comment]
That shouldn't happen due to the fingerprinting done. The only thing I can imagine is if the modified timestamps aren't getting updated:

https://github.com/cross-rs/cross/blob/8d8d84bc5f180b1e6b10121de6c072a618dc7f8e/src/docker/remote.rs#L549-L576

**Comment by Emilgardis** [comment]
The files are copied with `docker cp`, they just don't seem to stick. The fingerprinting is checked, files are marked as having been changed, but the copy doesn't work

**Comment by Emilgardis** [comment]
I wonder if this is a wider issue, does updating a persistant volume also not work?

**Comment by Alexhuszagh** [comment]
> I wonder if this is a wider issue, does updating a persistant volume also not work?

It should, I'm going to take a deep look at this. We've been adding new toolchains to persistent data volumes ever since we switched it so we only copy the base toolchain over during initial creation, and not the addition files for a specific target, and only copy those other files later when we're cross-compiling while using a persistent data volume.

So, this shouldn't be happening, and if it was, there should have been earlier signs this wasn't working.

**Comment by Alexhuszagh** [comment]
Manually verified this with running the code myself as well:

```bash
$ /usr/bin/docker run --userns host --name cross-stable-x86_64-unknown-linux-gnu-16b8c-a8314ef7d-x86_64-unknown-linux-gnu-issue1016-bb6bb --rm -v cross-stable-x86_64-unknown-linux-gnu-16b8c-a8314ef7d:/cross -v /cross/cargo/bin -it ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main bash
$ cat cross/home/ahuszagh/Desktop/cross/issue1016/src/main.rs
fn main() {
    println!("Hello, world!");
}
```

Or the file is unmodified. I'm unsure if the temporary directory, however, is populated. For example, for me, `/home/ahuszagh/.local/share/cross-rs/tmp/.tmpYDT6yw`.

**Comment by Alexhuszagh** [comment]
This shouldn't be happening, since `docker cp` is supposed to overwrite [files](https://docs.docker.com/engine/reference/commandline/cp/#description):

> - SRC_PATH specifies a file
>   - `DEST_PATH` does not exist: the file is saved to a file created at `DEST_PATH`
>   - `DEST_PATH` does not exist and ends with `/`: Error condition: the destination directory must exist.
>   - `DEST_PATH` exists and is a file: the destination is overwritten with the source file’s contents
>   - `DEST_PATH` exists and is a directory: the file is copied into this directory using the basename from SRC_PATH

The `-a` flag is supposed to just preserve the GID/UID [information](https://docs.docker.com/engine/reference/commandline/cp/#options):

> `--archive` , `-a`: Archive mode (copy all uid/gid information)

I'm not sure the cause of this, trying to debug the issue now. I wonder if the files are properly getting copied to the temp directory: I've seen that `docker cp -a` is properly invoked. The files **should** be copied to the temporary directory, since they are prior to fingerprinting.

**Comment by Alexhuszagh** [comment]
I think the best solution is the 2 step approach: otherwise, we will have to copy either a directory or tarballs **into** the container, then we can either have a script that writes into the destination recursively (with overwriting existing files), we can decompress a tarball (a second set of copies), or we can copy with overwrite from src to dst (a second set of copies). The remove then copy step uses logic we already have and avoids redundant copies (since we already have to copy into the temp directory, then to the Docker container).
