### ISSUE TITLE
error: failed to create directory `/target/release`

### ISSUE THREAD

**Issue by abcd-ca** [cross-rs/cross#1098]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

My project stopped cross compiling (even when I comment everything out except for a hello world). 

I'm sorry I don't know how to reproduce but my question is: Where is the location of whatever is being held onto that is preventing this from working. 

My command is, `cross build --verbose --release --target=armv7-unknown-linux-musleabihf`

The error I get is, "error: failed to create directory `/target/release`"

This project used to compile. I think I might have corrupted something by cancelling (ctrl-c on mac) during a cross build.

Here's the interesting bit: If I rename the root project folder (the one that contains my Cargo.toml) then re-run the command, it succeeds!

I have tried,

* `cargo clean`
* `cross clean`
* uninstalled cross, deleted `~/.cargo/git` and `~/.registry` folders, reinstalled cross 
* deleting all the docker containers and images that are related to this project and cross (I see no volumes to delete in docker)

### What target(s) are you cross-compiling for?

armv7-unknown-linux-musleabihf

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

1.64.0

### Example

1. `cd my-project`
2. `cross build --verbose --release --target=armv7-unknown-linux-musleabihf`. Fails, "error: failed to create directory `/target/release`"
3. Duplicate my project in macOS, name it my-project-copy
4. `cd ../my-project-copy`
5. `cross build --verbose --release --target=armv7-unknown-linux-musleabihf`. Succeeds! "Finished release [optimized] target(s) in 12.12s"

### Additional information / notes

I can reproduce the same issue with `aarch64-unknown-linux-gnu` target. It's all about the root project folder name.

**Comment by Emilgardis** [comment]
Can you post the verbose output of the failing build?

what version of cross are you actually using? You've shown us what version cargo is, but not cross

**Comment by abcd-ca** [comment]
@Emilgardis Thank you for taking a look. 

`cross --version` output:

``` 
cross 0.2.4 (a8082de 2022-10-26)
[cross] warning: `cross` does not provide a Docker image for target aarch64-apple-darwin, specify a custom image in `Cross.toml`.
[cross] note: Falling back to `cargo` on the host.
cargo 1.64.0 (387270bc7 2022-09-16)
```

Here is the verbose version of the failed output:

```
+ cargo metadata --format-version 1 --filter-platform aarch64-unknown-linux-gnu
+ rustc --print sysroot
+ /opt/homebrew/bin/docker
+ /opt/homebrew/bin/docker version -f '{{ .Server.Os }},,,{{ .Server.Arch }}'
+ rustup toolchain list
+ rustup target list --toolchain stable-x86_64-unknown-linux-gnu
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
+ /opt/homebrew/bin/docker run --userns host --platform linux/amd64 -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/Users/foo/.xargo' -e 'CARGO_HOME=/Users/foo/.cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e TERM -e 'USER=foo' -e 'CROSS_RUSTC_MAJOR_VERSION=1' -e 'CROSS_RUSTC_MINOR_VERSION=64' -e 'CROSS_RUSTC_PATCH_VERSION=0' --name cross-stable-x86_64-unknown-linux-gnu-f34a5-a55dd71d5-aarch64-unknown-linux-gnu-6fd58-1667084184472 --rm --user 501:20 -v /Users/foo/.xargo:/Users/foo/.xargo:z -v /Users/foo/.cargo:/Users/foo/.cargo:z -v /Users/foo/.cargo/bin -v /Users/foo/Documents/projects/my-project:/Users/foo/Documents/projects/my-project:z -v /Users/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/Users/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:z,ro -v /Users/foo/Documents/projects/my-project/target:/target:z -w /Users/foo/Documents/projects/my-project -t ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main sh -c 'PATH="$PATH":"/Users/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin" cargo build --verbose --release --target=aarch64-unknown-linux-gnu'
error: failed to create directory `/target/release`

Caused by:
  No such file or directory (os error 2)
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
```

**Comment by Alexhuszagh** [comment]
Can you check the permissions of `/Users/foo/Documents/projects/my-project/target/`? `ls -la /Users/foo/Documents/projects/my-project/target/`. It sounds like something is running with elevated permissions before, and then is running without permission to modify the folder inside container image.

The other major issue possible: are you using rootless docker? If so, you need to set `CROSS_ROOTLESS_CONTAINER_ENGINE=1` since it's difficult to detect if a container engine is using root or rootless without numerous calls to the client, so we just assume `docker` runs as root and `podman` runs as the user. If you're using rootless docker, you won't have permissions to modify anything on the host filesystem.

**Comment by abcd-ca** [comment]
@Alexhuszagh Thank you.

I can reproduce the problem of the parent directory name when the target folder does not exist (has been deleted). The target folder gets created only if it succeeds so I can only show you the permissions of the target folder after a successful build:

```
drwxr-xr-x   8 foo  staff   256 29 Oct 16:25 .
drwxr-xr-x@ 19 foo  staff   608 29 Oct 16:16 ..
-rw-r--r--   1 foo  staff  2816 29 Oct 16:33 .rustc_info.json
drwxr-xr-x   4 foo  staff   128 29 Oct 16:04 aarch64-unknown-linux-gnu
drwxr-xr-x   6 foo  staff   192 29 Oct 16:26 armv7-unknown-linux-musleabihf
drwxr-xr-x   8 foo  staff   256 29 Oct 16:25 debug
drwxr-xr-x   8 foo  staff   256 29 Oct 16:04 release
drwxr-xr-x   2 foo  staff    64 29 Oct 16:25 tmp
```

I am certainly using docker and not podman. I don't know the answer about rootless but maybe this means something to you? `docker context ls` output:

```
NAME            DESCRIPTION                               DOCKER ENDPOINT                                KUBERNETES ENDPOINT                                    ORCHESTRATOR
default *       Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                    https://api.telusdigital.openshift.com:443 (o-about)   swarm
desktop-linux                                             unix:///Users/foo/.docker/run/docker.sock
```

I assume my Docker runs the same whether my parent folder is named `my-project` or `my-project-copy`?

**Comment by Alexhuszagh** [comment]
> of the parent directory name when the target folder does not exist (has been deleted)

That's odd, since we create the target directory in `cross` itself, and not in the container, since any mounted folders are auto-created by Docker and will always have root permissions. See [create_target_dir](https://github.com/cross-rs/cross/blob/a8082decd46d260ae8e2bf13ebb251516dd8415e/src/docker/shared.rs#L814-L826).

Looks like it's using the default root-based configuration. A quick test just to confirm 100% would be the following code:

```bash
$ docker run -it --rm -v "$PWD":/out ubuntu:20.04 touch /out/file
$ ls -la file
ls -la file
-rwxrwxrwx 1 ahusz ahusz 0 Oct 29 19:04 file
```

This was running rootless, if I ran it as root, the owner would be `root:root`. This avoids setting the `--user` flag so it runs as if it were root inside the container: for podman or rootless Docker, this will mean anything outside the container has normal user permissions. For Docker using root permissions, it would then have root permissions. Otherwise, everything looks normal.

> I assume my Docker runs the same whether my parent folder is named my-project or my-project-copy?

It should be fine: both are valid path names and don't have any of the caveats Docker might complain about (`:` in the path name). 

At this point, I wonder if the group ID and the user ID not matching is the issue? It shouldn't be... Can you try running the above command with the UID/GID values?

```bash
$ docker run -it --rm --user 501:20 -v "$PWD":/out ubuntu:20.04 touch /out/file
```

**Comment by abcd-ca** [comment]
@Alexhuszagh I checked again, deleting the target folder in my mac host and re-ran the cross build which recreated the target folder again in the host. That's what I checked the permissions on (once generated) – is that want you wanted or did you want the permissions of the target folder inside the docker container?

This is the `ls -la` output of the `target` folder inside the docker container, in case that's helpful:

```
drwxr-xr-x  6 501 dialout 192 Oct 30 02:20 .
drwxr-xr-x 19 501 dialout 608 Oct 30 02:20 ..
-rw-r--r--  1 501 dialout 503 Oct 30 02:20 .rustc_info.json
-rw-r--r--  1 501 dialout 176 Oct 30 02:20 CACHEDIR.TAG
drwxr-xr-x  4 501 dialout 128 Oct 30 02:20 armv7-unknown-linux-musleabihf
drwxr-xr-x  8 501 dialout 256 Oct 30 02:20 release
```

output of the first touched file via ubuntu container: `-rw-r--r--  1 foo  staff  0 29 Oct 19:25 file`

output of the second touched file with user flag: `-rw-r--r--  1 foo  staff  0 29 Oct 19:30 file`

Thank you for your help so far. Cross is great, I really like it, generally.

**Comment by Alexhuszagh** [comment]
This is very interesting, because it seems that `CACHEDIR.TAG` is written without write performissions, which is what `cross` itself writes on the host. So is `rustc_info.json` which is the fingerprint data. But oddly, they have the same gid and uid as normal, while those run in the container use the normal user (which is very, very odd), which should be using the same user and group ID as [normal](https://github.com/cross-rs/cross/blob/a8082decd46d260ae8e2bf13ebb251516dd8415e/src/id.rs#L6-L29).

Can you try using `--target-dir` for somewhere out-of-source? Like, `--target-dir ../build-dir`?

**Comment by abcd-ca** [comment]
side note – if I rename the folder it does a full re-build. If I put my command inside a .sh script and run the shell script it does a full rebuild.

**Comment by abcd-ca** [comment]
1. renamed my parent folder from my-project-copy back to the original, previously-problematic, "my-project"
2. `cross build --target-dir ../foo --release --target=aarch64-unknown-linux-gnu`. Success – creates a new, "foo" folder above the parent one containing the binaries
4. deleted `my-project/../foo folder` and `my-project/target` folder
3. `cross build --release --target=aarch64-unknown-linux-gnu`. Success - creates target folder (this is what wasn't working before when I originally opened the GH issue). 
4. `cross build --release --target=armv7-unknown-linux-musleabihf`. Success

Weird. Seems like by specifying the `--target-dir` once, it resolved the issue – maybe the cache I am imagining was purged with a change of target dir; deleting something that had something corrupt or incorrect permissions?

**Comment by Alexhuszagh** [comment]
That sounds like it might have been the issue, I'm very happy it's working again. I wonder since you didn't have write permissions for `target/CACHEDIR.TAG`.  This is especially odd though since the `-f` flag would have removed it, and `cargo clean` automatically cleans up the target directory even in those cases.

**Comment by abcd-ca** [comment]
Thanks for helping!

**Comment by mcandre** [comment]
In my case, the failure to create a directory (and other Docker failures), appear to be the result of a longstanding failure of Docker becoming corrupted when the host resumes from hibernation.

For example, if you do a lot of work with cross or Docker over several days, close the laptop lid, open the laptop lid, and try to keep working.

Fortunately, restarting the Docker service temporarily restores Docker to a working state, until the next time it goofs up. For example, on macOS hosts.

This hibernation issue is worth raising to the Docker maintainers. Until they iron out the low level details, I would like to see Docker *automatically* restart upon resuming from hibernation.
