### ISSUE TITLE
Cross compile issue when using egui / eframe crates 

### ISSUE THREAD

**Issue by macbryla** [cross-rs/cross#1140]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

cross compile not working when using eframe crate 
cross compile works on a simple 'hello world' rust application 

Cargo.toml
[dependencies]
eframe = "0.19.0"
egui = "0.19.0"

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4

### Example

cross build --release --target aarch64-unknown-linux-gnu

// get the following error
--- stderr
  thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"` did not exit successfully: exit status: 1
  error: could not find system library 'fontconfig' required by the 'servo-fontconfig-sys' crate

  --- stderr
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  ', /cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by Alexhuszagh** [comment]
Compiling crates with external C/C++ dependencies requires those dependencies to be installed, either as part of the build process or using custom package managers. For this project, [eframe](https://github.com/emilk/egui/tree/master/crates/eframe) clearly lists the dependencies:

```bash
sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
```

For cross, you need to install them for the target architecture, and also, because we're in a non-interactive context, export `DEBIAN_FRONTEND=noninteractive`. A sample [project](https://github.com/Alexhuszagh/issue_1140) using `eframe` and `egui` compiles fine with the following `Cross.toml`:

```toml

[target.aarch64-unknown-linux-gnu]
pre-build = [
	"export DEBIAN_FRONTEND=noninteractive",
	"dpkg --add-architecture $CROSS_DEB_ARCH",
	"apt-get update && apt-get install -y libxcb-render0-dev:$CROSS_DEB_ARCH libxcb-shape0-dev:$CROSS_DEB_ARCH libxcb-xfixes0-dev:$CROSS_DEB_ARCH libspeechd-dev:$CROSS_DEB_ARCH libxkbcommon-dev:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH",
]
```

Notice how we use `CROSS_DEB_ARCH` to specify the target architecture, so `libxcb-render0-dev` becomes `libxcb-render0-dev:$CROSS_DEB_ARCH`. More info on working with external dependencies can be found on our [wiki](https://github.com/cross-rs/cross/wiki/FAQ#external-dependencies). If you have any further questions, feel free to reach out in our [discussions](https://github.com/cross-rs/cross/discussions) or our matrix [room](https://matrix.to/#/#cross-rs:matrix.org).

**Comment by macbryla** [comment]
Thank you.
