### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by JosuGZ** [cross-rs/cross#1175]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request

### Describe your request

I would like to be able to run the containers on interactive mode.

### Describe why this would be a good inclusion for `cross`

This could be useful to troubleshot build problems. For instance, right now `git describe` is not working on some of my targets.

I can of course do that by hand, but getting a terminal into the containers could be interesting. Something like `cross interactive --target foo`.

**Comment by Alexhuszagh** [comment]
This wouldn't be in `cross` due the need for complete API compatibility (so any CLI flags should be processed identical by cargo and cross), but could be used for `cross-util`. The downside is the implementation is a bit non-trivial, since we'd:
- Need to process all the package and config data
- Parse the command line options
- If using remote, do everything like that
- Add an interactive mode to add the `-i` flag
- Change it to use `bash` or `sh` for interactive mode (likely would require `sh` since with custom containers we can't guarantee the presence of `bash`).

All of this is doable, just most of it isn't currently exposed to `cross-util` without some refactoring.

**Comment by Alexhuszagh** [comment]
I guess potentially we could have a `cross-util cargo` subcommands or similar which would process the command-line flags but also allow custom cross extensions.

**Comment by kingosticks** [comment]
Won't https://github.com/cross-rs/cross/pull/1280 allow you to now do this? I'm using it to debug and run `cargo-deb`.

**Comment by Emilgardis** [comment]
You'd be correct @kingosticks, thanks! We also have #716 which is a bit more specific but not solved with #1280
