### ISSUE TITLE
Docs request: add info about x86_64-unknown-linux-gnu toolchain to "Getting Started"

### ISSUE THREAD

**Issue by tgross35** [cross-rs/cross#1192]
I ran into the issue at this discussion: https://github.com/cross-rs/cross/discussions/1161 and it was pretty tough to find the solution. Would it be possible to document this issue in the getting started guide?

The message is just pretty confusing, since my target isn't even `x86_64-unknown-linux-gnu`. I assume it needs that installed to build in Docker, so isn't this a problem for all non-linux users?

**Comment by Emilgardis** [comment]
Hi!

What error message did you get? We could definitely add something about it, just need more information about the problem.

**Comment by tgross35** [comment]
Wow that was fast, my error was exactly the same as in that discussion link:

```sh
tmgross@local cortex-m-quickstart % cross build --target thumbv7em-none-eabihf
Error: 
   0: `rustup target list --toolchain stable-x86_64-unknown-linux-gnu` failed with exit status: 1

Stderr:
   error: toolchain 'stable-x86_64-unknown-linux-gnu' does not support components
```

The wording is just kind of tricky because it looks similar to a missing target - which I'm used to. But I never realized you could install toolchains and not just targets, so mega confusion when `rustup target list` happily reported that `x86_64-unknown-linux-gnu` is installed.

Do you have any idea what causes this problem? Because I'm positive I didn't run into it before on the same machine, only when I tried it today

**Comment by Emilgardis** [comment]
As an explainer, `cross` installs via `rustup` targets for cross-compilation, and mounts the toolchain with that target in a docker container.

A rust toolchain is the collection of `rustc`, `cargo` etc etc, these binaries are compiled to run on a specific architecture/host.
A rust target is what the rust toolchain uses to compile for a specific architecture/host. By default, a toolchain will have the target for its own arch, but more targets can be installed.

So if your system is say an M1 macbook, all that is needed for `cross` is rustup and a proper, rustup maintained, `x86_64` toolchain installed, where we can install new targets and add components (like `rust-src` etc).

the error message `error: toolchain 'stable-x86_64-unknown-linux-gnu' does not support components` says that rustup can't check the toolchain which means that we can't check the it for the presence of additional targets, so we quit.

This underlying issue might be https://github.com/rust-lang/rustup/issues/1793#issuecomment-485738454, which doesn't explain what actually happened.

I think the best solution here is actually to give a suggestion to the user when we see this error message, since we know how to solve it.


So maybe something like

```
Error: 
   0: `rustup target list --toolchain stable-x86_64-unknown-linux-gnu` failed with exit status: 1

Stderr:
   error: toolchain 'stable-x86_64-unknown-linux-gnu' does not support components
Suggestion: try reinstalling the 'stable-x86_64-unknown-linux-gnu' toolchain
   $ rustup toolchain uninstall stable-x86_64-unknown-linux-gnu
   $ rustup toolchain install stable-x86_64-unknown-linux-gnu
```

and if the default toolchain is another architecture, we can add a note

`Note: cross uses the 'x86_64-unknown-linux-gnu' toolchain for mounting rust`

**Comment by Emilgardis** [comment]
I've opened #1193 for doing a suggestion when encountering the error, and added a mention in the wiki https://github.com/cross-rs/cross/wiki/Getting-Started#cross-compiling-your-first-package

**Comment by tgross35** [comment]
Thank you for the super thorough explanation, and for the updates! Makes sense, I never really understood how cross does splits what is done native with what is done in Docker.

Fwiw - I am on an x86 mac, and I definitely used cross successfully a couple months ago without doing this fix. I also use it in CI on some x86 macs, so I don’t know why it seemed to stop working recently
