### ISSUE TITLE
proc-macro crate type doesn't work becuase it should be run on the host

### ISSUE THREAD

**Issue by parched** [cross-rs/cross#123]
Tests for a proc-macro crate should be run on the host but it looks like cross tries to run them on the target and fails.

## Repro
For a proc macro crate run `cross test --target=<not your host target>`

**Comment by japaric** [comment]
Hmm, I'm not quite sure why the unit test runner is a host binary but integration tests (the stuff in the `tests` directory) are target binaries. This is very different from what happens in non proc-macro crates where everything is target binaries. But I suppose it makes sense because proc macro are only ever evaluated in the host.

In any case, I'd say that the Cargo runner is not handling correctly this case since is passing a x86_64 binary to QEMU, which is the runner for the target:

``` console
# bad: QEMU with x86_64 binary
$ cross test --target aarch64-unknown-linux-gnu --lib -v
     Running `qemu-aarch64 /target/debug/deps/foo-6528439a7d43cbc3`
/target/debug/deps/foo-6528439a7d43cbc3: Invalid ELF image for this architecture
error: test failed, to rerun pass '--lib'

$ file target/debug/deps/foo-6528439a7d43cbc3
target/debug/deps/foo-6528439a7d43cbc3: ELF 64-bit LSB shared object, x86-64

# ok
$ cross test --target aarch64-unknown-linux-gnu --tests -v
$      Running `qemu-aarch64 /target/aarch64-unknown-linux-gnu/debug/deps/idempotence-ca25ef3b4eddd762`

running 1 test
(..)
```

I think that fixing the Cargo runner issue would make this use case work with Cross v0.1.12 (not yet released).

It seems relatively easy to work around this issue in the meantime: use `cargo test --lib`, in the host build only, to run the unit tests and `cross test --target $T --tests` to run integration tests on the targets.

**Comment by parched** [comment]
Yes, I figured I could work around I just didn't get that far yet. I'm not familiar enough Cargo sorry, does it choose a runner based on `--target` ? How do cross change the runner?

**Comment by japaric** [comment]
The "runner" is a relatively new Cargo feature. It's normally used like this:

``` toml
# .cargo/config
[target.armv7-unknown-linux-gnueabi]
runner = "qemu-arm"
```

With that file in the Cargo project Cargo will run executables compiled for ARM using `qemu-arm`; binaries compiled for other targets will be executed directly.

> does it choose a runner based on --target ?

If you use `--target $T` then Cargo will run all the produced binaries using `target.$T.runner`. But, I think it should make an exception in the case of the unit test runner of proc-macro libraries, since it's a host binary.

> How does cross change the runner?

Cross v0.1.12 will use the env variable counterpart of the .cargo/config setting: for example, `CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABI_RUNNER`. That's variable will be set in the Docker environment.

**Comment by parched** [comment]
Ok thanks, I understand now. Yes cargo should definitely do that, I'll raise a ticket there.

**Comment by parched** [comment]
This looks like the relevant bug https://github.com/rust-lang/cargo/issues/4336

**Comment by Alexhuszagh** [comment]
This no longer seems to reproduce, using the procedural macro based on this [blog](https://blog.logrocket.com/procedural-macros-in-rust/) (not hosting the code inline since there's no license provided).

Using that macro `Describe`, I think have in my `/tests` directory the following test:

```rust
#![allow(unused)]

use derive_macro::Describe;

#[derive(Describe)]
enum TestEnum {
    VariantA,
    VariantB,
}

#[derive(Describe)]
struct TestStruct {
    string: String,
    enumeration: TestEnum,
    float: f64,
}

#[test]
fn test_describe() {
    TestEnum::describe();
    TestStruct::describe();
}
```

Running the following all work:

```bash
$ cross run --target aarch64-unknown-linux-gnu
$ cross run --workspace --target aarch64-unknown-linux-gnu
$ cross test --workspace --target aarch64-unknown-linux-gnu
$ cd derive-macro/
$ cross test --target aarch64-unknown-linux-gnu
```

If this fails for more complex proc macros, I'll re-open this.

**Comment by Alexhuszagh** [comment]
Duplicate of #605.
