### ISSUE TITLE
minor CVE

### ISSUE THREAD

**Issue by mcandre** [cross-rs/cross#1236]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

cargo audit reports a low level CVE in cross' dependency tree.

```console
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 537 security advisories (from /Users/andrew/.asdf/installs/rust/1.64/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (98 crate dependencies)
Crate:     atty
Version:   0.2.14
Warning:   unsound
Title:     Potential unaligned read
Date:      2021-07-04
ID:        RUSTSEC-2021-0145
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0145
Dependency tree:
atty 0.2.14
├── supports-color 1.3.1
│   └── owo-colors 3.5.0
│       ├── cross 0.2.5
│       │   └── rocky 0.0.1
│       └── color-eyre 0.6.2
│           └── cross 0.2.5
├── cross 0.2.5
└── clap 3.2.23
    └── cross 0.2.5

warning: 1 allowed warning found
```

Strangely, when I run `cargo audit` again, then it no longer shows this warning.

https://crates.io/crates/cargo-audit

Are we including `cargo audit` in the CI/CD pipeline? Unfortunately, dependabot does not appear to run `cargo audit` yet.

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

0.2.5

**Comment by Emilgardis** [comment]
Dependabot does have data from rustsec, see https://github.blog/2022-06-06-github-brings-supply-chain-security-features-to-the-rust-community/ fyi!

Yes, we do run it via [`cargo-deny`](https://github.com/cross-rs/cross/blob/bb3df1b89d64efd42201737e390fe924f39f328c/.github/workflows/ci.yml#L23-L27), we also have dependabot enabled

We've fixed this in https://github.com/cross-rs/cross/pull/1151 I don't think this CVE requires a bump, especially since the CVE seems [to only affect custom global allocators](https://rustsec.org/advisories/RUSTSEC-2021-0145)

> In practice however, the pointer won't be unaligned unless a custom global allocator is used.
