### ISSUE TITLE
Some tust target not installed in docker

### ISSUE THREAD

**Issue by yhw2003** [cross-rs/cross#1571]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I got error`error[E0463]: can't find crate for core`  in longarch cpus targets . You can see my ci logs.
[Actions](https://github.com/yhw2003/NjtechQuickLogin/actions/runs/11262718817/job/31319024381)

### What target(s) are you cross-compiling for?

loongarch64-unknown-linux-gnu, loongarch64-unknown-linux-musl

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [X] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

0.2.5

**Comment by unfixa1** [comment]
Make sure you have installed the correct toolchain for loongarch64. You can use the following command to add the target:
rustup target add loongarch64-unknown-linux-gnu
rustup target add loongarch64-unknown-linux-musl
It may also be that docker conflicts with other containers
You can use servbay instead of docker, [servbay](servbay.com) is better than docker on mac

**Comment by Emilgardis** [comment]
Make sure your using cross from the main branch
Look at line 4 in that CI step

`cross install cross --git https://github.com/cross-rs/cross/`

You can also change Cross.toml to include this new target
