### ISSUE TITLE
Support qemu-user emulation for real i586, i686, and x86_64 CPUs

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#162]
I'd like to be able to, optionally,

- test x86 on `qemu-user`,
- specify a particular cpu.

Currently, just because `cross` is able to cross-compile for `i586` and `i686` but the tests are run on a `x86_64` CPU. That is, if the software targeting `i586` uses an instruction that is not available in that architecture, but is available on `x86_64`, it can pass the tests, but fail in the real world.

**Comment by jamesmunns** [comment]
Sounds good to me, let me know if you need help implementing!

**Comment by Alexhuszagh** [comment]
This is now possible since we allow the `CROSS_TARGET_${TARGET}_RUNNER` environment variable, the `target.(...).runner` TOML config option, and also ensure the any Cargo-specific environment variables are passed to the container. This is documented now on the [wiki](https://github.com/cross-rs/cross/wiki/FAQ#customizing-runners).

For example, the following will run all binaries for `aarch64-unknown-linux-gnu` on the Cortex-A72:

```bash
$ export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER="qemu-aarch64 -cpu cortex-a72"
$ cross run --target aarch64-unknown-linux-gnu
```
