### ISSUE TITLE
Support wasm-unknown-unknown

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#175]
The title says it all.

**Comment by Alexhuszagh** [comment]
As cross-rs is no longer part of rust-embedded, and since `no_std` packages can be built without issue with cargo itself, this no longer is within the scope of cross. Only `no_std` packages seem to work at this time, since panic abort and panic unwind do not work currently for the target. More documentation on the status of the target is [here](https://doc.rust-lang.org/rustc/platform-support/wasm64-unknown-unknown.html).

```bash
$ $ cargo +nightly build --target wasm64-unknown-unknown -Zbuild-std=core
   Compiling nostd v0.1.0 (/home/ahuszagh/Desktop/cross/nostd)
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
```
