### ISSUE TITLE
cross should use `docker --mount` instead of `docker --volume`

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#202]
`docker --mount` seems to be the "recommended" way of handling volumes nowadays, `cross` should use that.

**Comment by GeoffClements** [comment]
However, according to the docker site, there are no plans to depricate "-v" and there may be many older implentations out there. Perhaps use --mount with a fall-back to -v?

**Comment by Alexhuszagh** [comment]
I don't believe this is a good idea, since the main differences seem to be the simplicity and readability of the result, but mount is very verbose. Since we programmatically generate our docker arguments and only bind host directories to container ones (IE, only using bind mounts), extra verbosity doesn't seem to be an advantage here. According to the [documentation](https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag):

> --mount: Consists of multiple key-value pairs, separated by commas and each consisting of a <key>=<value> tuple. The --mount syntax is more verbose than -v or --volume, but the order of the keys is not significant, and the value of the flag is easier to understand.

This doesn't matter, since we're programmatically generating these anyway, and the source and destination directory are quite clear. The focus isn't on the docker command: it's on the Rust we use to generate it. I'm of the opinion that the volume syntax is more readable here.

```rust
// Using volume syntax
docker.args(&[
    "--volume",
    &format!("{}:{}:ro", host_root.display(), mount_root.display()),
]);
// Using mount syntax
docker.args(&[
    "--mount",
    &format!("type=bind,source={},target={},readonly", host_root.display(), mount_root.display()),
]);
```

This would generate the following docker arguments (as examples):

```bash
# Using volume syntax
--volume "$(host_root)":"$(mount_root)":ro
# Using mount syntax
--mount type=bind,source="$(host_root)",target="$(mount_root)",readonly
```

> The --mount flag does not support z or Z options for modifying selinux labels.

This is an issue, since we use these [labels](https://github.com/cross-rs/cross/blob/e4d429d9e77f5466fcc6d529ff141fe7df513551/src/docker.rs#L217-L231).

As docker's documentation [specifies](https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior):

> Because the -v and --volume flags have been a part of Docker for a long time, their behavior cannot be changed. This means that there is one behavior that is different between -v and --mount

So there are no plans to remove volume, and it supports the features we want.
