### ISSUE TITLE
BSD cross test support

### ISSUE THREAD

**Issue by Dylan-DPC-zz** [cross-rs/cross#220]
* x86_64-unknown-dragonfly
* x86_64-unknown-freebsd
* x86_64-unknown-netbsd

and, the support matrix, shows that none of these can run tests. 

_Originally posted by @gnzlbg in https://github.com/rust-embedded/cross/issues/40#issuecomment-432543207_

**Comment by gnzlbg** [comment]
@malbarbo IIRC the `libc` crate does run tests in `freebsd` under `qemu-system`, is that correct ?

**Comment by malbarbo** [comment]
Yes, that's correct.

To run the tests a disk image with the test files are created, then the qemu is booted with the os image and the disk test image, finally a custom init scrip run the tests. See https://github.com/rust-lang/libc/blob/master/ci/run.sh#L43

The qemu image used by libc was manually created. I think we would want an automatically build one.

**Comment by asomers** [comment]
Running tests on FreeBSD under QEMU is slow and awkward.  Using www.cirrus-ci.com (available since about January 2019) is a much better option.

**Comment by Alexhuszagh** [comment]
Closing this, since it's difficult without [full system emulation](https://stackoverflow.com/a/3383680/4131059), which is quite slow. We can't ship FreeBSD images with Linux binary compatibility either, due to issues with running [FreeBSD images inside Docker](https://stackoverflow.com/a/33864293/4131059). Therefore, it's up to the user to get their own FreeBSD instance up and running, such as on a [cloud service](https://www.freebsd.org/commercial/isp/).
