### ISSUE TITLE
cross build --target x86_64-pc-windows-msvc => error: linker `link.exe` not found

### ISSUE THREAD

**Issue by theronic** [cross-rs/cross#238]
Compiling for Windows on OSX seems to require non-zero configuration :).

**Comment by paulrberg** [comment]
Indeed. I am getting the following error log on macOS@10.15.7 and cross@0.2.1:

```
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `lazy_static`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: build failed
```

**Comment by schell** [comment]
I'm getting this same error trying to `cross build --target x86_64-apple-darwin` from `aarch64-apple-darwin`.

**Comment by GCSBOSS** [comment]
I'm getting this error on GitLab Pipelines, using the rust container image. Below my job:
```yaml
build:
  image: rust
  stage: build
  tags:
    - docker
  script:
    - cargo build --release --target x86_64-unknown-linux-gnu
    - rustup target add x86_64-pc-windows-msvc
    - cargo build --release --target x86_64-pc-windows-msvc
```
This is the exact error:
```
error: linker `link.exe` not found
  |
  = note: No such file or directory (os error 2)
note: the msvc targets depend on the msvc linker but `link.exe` was not found
note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option
error: aborting due to previous error
error: could not compile `hyper`
To learn more, run the command again with --verbose.
```

And looking at it again, might be an issue with some specific dependency 🤔

**Comment by Alexhuszagh** [comment]
We don't support images for any of those targets, since we cannot distribute images containing MSVC or the macOS SDK. We now warn you if `cross` falls back to `cargo` on the host, and we also have [Dockerfiles](https://github.com/cross-rs/cross-toolchains) so you can build images to cross-compile for MSVC and Darwin targets.

**Comment by andrewbaxter** [comment]
FWIW the warning is the first line of the output and almost immediately gets flushed from the output on a new build by `Compiling ...` lines.

Just some thoughts:

1. If someone's cross compiling, is it ever desirable to fall back to the local cargo? Maybe (erring on the side of safety) it should fail immediately instead of proceed, with a flag to try with the local cargo if desired?
2. Failing that, logging it at the end might make it more visible.
3. A note up front about windows builds would be great - I came to the readme and saw `“Zero setup” cross compilation and “cross testing” of Rust crates` and thought "great!", read the getting started steps, and got a build failure.  Adding a warning/note about platforms that aren't zero-config prominently in the readme might reduce the surprise of failures and allow people to avoid searching (closed) issues to find the solution.
4. I also checked the wiki, but there's nothing there about windows/msvc AFAICT.  Would having a section there be a better place for this information?

**Comment by Emilgardis** [comment]
> Just some thoughts:
> 
>     1. If someone's cross compiling, is it ever desirable to fall back to the local cargo? Maybe (erring on the side of safety) it should fail immediately instead of proceed, with a flag to try with the local cargo if desired?

I agree, see https://github.com/cross-rs/cross/issues/1591

>     2. Failing that, logging it at the end might make it more visible.

yes, this would be easy to implement also.

>     3. A note up front about windows builds would be great - I came to the readme and saw `“Zero setup” cross compilation and “cross testing” of Rust crates` and thought "great!", read the getting started steps, and got a build failure.  Adding a warning/note about platforms that aren't zero-config prominently in the readme might reduce the surprise of failures and allow people to avoid searching (closed) issues to find the solution.
>     4. I also checked the wiki, but there's nothing there about windows/msvc AFAICT.  Would having a section there be a better place for this information?

The problem here is that the slightly optimistic claim is only for our supported targets, which we list on the README. Maybe we could add a side-note about unsupported targets but seems unneccessary. I'd be open for further discussion and/or PRs improving but this 3 year old issue is probably not the place for it!

**Comment by andrewbaxter** [comment]
Oh, #1591 , nice!

Sorry, I searched a bit and thought this was where discussion had ended so I thought this would be the most relevant place.  Should I create new issues/discussions for any of them?  FWIW I ran into other Windows build issues (not cross related) so I'm kind of exploring other options now, but I keep coming back to Windows builds about once a year so I wanted to open discussion.

**Comment by Emilgardis** [comment]
Please do 👍🏼
