### ISSUE TITLE
Consider adding an option to run under full-system emulation

### ISSUE THREAD

**Issue by nagisa** [cross-rs/cross#242]
Something along the lines of

```
qemu-system-X -kernel kernel -initrd initrd -append init=executable
```

Should be sufficient, although it will be necessary to wrap `executable` into some sort of script that would

1. cleanly terminate the system after it is done running the `executable`;
2. transfer the exit code from the guest to the host somehow...

Obviously there are a number of complications as well (e.g. dynamic library dependencies), but for targets that do not work either way currently (s390x, sparc64, (to an extent) powerpc...) it may prove to be a viable alternative that gives significant stability boost.

As an extended future goal this could also support testing and building on various other kernels that aren’t linux!

**Comment by Alexhuszagh** [comment]
I believe this was implemented in #153 with the wrapper script of `/linux-runner`. Since you can also provide your own `CARGO_TARGET_${TARGET}_RUNNER` envvar to your custom runner if you use custom [Dockerfiles](https://github.com/cross-rs/cross/wiki/Configuration#builddockerfile), you can fine-tune this if needed.
