### ISSUE TITLE
armv7-unknown-linux-musleabihf suddenly failing tests on latest rust (1.39.0)

### ISSUE THREAD

**Issue by rossmacarthur** [cross-rs/cross#343]
https://travis-ci.org/rossmacarthur/sheldon/jobs/608753799

```
fatal runtime error: failed to initiate panic, error 9

qemu: uncaught target signal 6 (Aborted) - core dumped

error: process didn't exit successfully: `qemu-arm /target/armv7-unknown-linux-musleabihf/debug/deps/sheldon-4be4084973670074` (signal: 6, SIGABRT: process abort signal)
```

**Comment by Alexhuszagh** [comment]
I've tested this on the latest cross version, and this seems to work now:

```bash
cargo install cross --git https://github.com/cross-rs/cross
git clone --depth 1 --branch 0.6.6 https://github.com/rossmacarthur/sheldon
cd sheldon
cross build --target armv7-unknown-linux-musleabihf
cross test --target armv7-unknown-linux-musleabihf
```

I didn't use more recent Dockerfiles, since they use musl libc v1.2.0, which uses 64-bit `time_t` (see #478) which rust and libc don't support yet. The version info I'm using is:

- cross 0.2.1 (459e03e 2022-05-26)
- cargo 1.61.0 (a028ae4 2022-04-29)

Let me know if you want me to try on an older release or tag, since a patch may have changed things. Your [CI](https://github.com/rossmacarthur/sheldon/runs/5613274676?check_suite_focus=true) also suggests the same.
