### ISSUE TITLE
Recommended way of adding additional libraries to link against

### ISSUE THREAD

**Issue by shaunmulligan** [cross-rs/cross#35]
@japaric thanks for this awesome project!! 
I was just wondering how some one should go about adding additional libraries that need to be linked against. Some projects like https://github.com/plietar/librespot require additional dependencies such as `portaudio19-dev` and maybe some others. I was just wondering what is the appropriate method for adding these into cross so that the project builds correctly.

**Comment by japaric** [comment]
Simplest way: build the library as a *static* library in a build script and link to that.

If you want to link to a shared library and you are using the `pkg-config` crate, then you basically *can't* cross compile because that crate doesn't support cross compilation scenarios (AFAIK).

If you want to link to a cross compiled shared library provided by ubuntu, e.g. `libfoo-dev:i386`, or against a shared library that you intent to build manually, you'll have to override the docker and the only way to do that is to create a *local* image named, for example, `japaric/i686-unknown-linux-gnu:v0.1.3` because that's what `cross` expects it to be called.

I suggest you base that local image on the ones `cross` uses by default. So you could use something like this for the Dockerfile:

``` dockerfile
FROM japaric/i686-unknown-linux-gnu:v0.1.3

# Or build it yourself
RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install --no-install-recommends -y libfoo-dev:i386
```

**Comment by iav** [comment]
This method, and code from main page, not work.
Because `Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/binary-armhf/Packages`, same for 
```
FROM rustembedded/cross:aarch64-unknown-linux-gnu-0.1.16

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install libfoo:arm64
```
` Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/main/binary-arm64/Packages  404  Not Found`
Because `trusty` have only amd64 and i386 architectures in repos.

**Comment by gdesmott** [comment]
I'd suggest to close this as a dup of #149 as that's basically the same issue and this ticket contains extra information about how to make this work.

**Comment by rvolgers** [comment]
If I understand correctly, this is precisely what was fixed in https://github.com/rust-embedded/cross/commit/3b07a08aa8739a9f22450ceecc56531d108661d5

**Comment by Alexhuszagh** [comment]
We've documented this now extensively on the wiki, including the following examples:
- [Using Debian Repositories](https://github.com/cross-rs/cross/wiki/FAQ#using-debian-repositories)
- [Linking External Libraries](https://github.com/cross-rs/cross/wiki/FAQ#linking-external-libraries)

We've also included complete projects using examples both with pre-build hooks and custom Docker images for this purpose.
- [dbus](https://github.com/cross-rs/wiki_assets/tree/main/FAQ/dbus)
- [openssl-certs](https://github.com/cross-rs/wiki_assets/tree/main/Recipes/openssl-certs)
