### ISSUE TITLE
Add #121 to caveats

### ISSUE THREAD

**Issue by siku2** [cross-rs/cross#399]
The README currently mentions the following caveat:
> path dependencies (in Cargo.toml) that point outside the Cargo project won't work because cross use docker containers only mounts the Cargo project so the container doesn't have access to the rest of the filesystem.

However this doesn't make it clear that it's not possible to access paths IN the container outside of the project directory. Trying to do so is met with a `PermissionDenied` error.

This is unfortunate, because there are crates that create (or at least *try to* create) files in the home directory during installation (For example [Amethyst](https://amethyst.rs/)).
There has already been an issue about this (#121) a few years ago but it was deemed to be working as intended.
Fair enough, I have no problem with that but I believe it should be made more clear.
I ended up setting `DOCKER_OPTS` to `"--user root"` which might not be ideal, but it works.

A single sentence mentioning this could potentially save a lot of headaches. What do you think?

**Comment by Alexhuszagh** [comment]
The issue actually wouldn't be for the home directory that it's a permissions issue: it's that the home directory for the user doesn't exist, actually. So anything that the user would normally have access to, they can use. This includes the temp directory. Unfortunately, since we do not know user ID of the current user necessarily, we can't pre-create a user directory in the HOME directory. However, using volume mounts you can do this:

You can fix this by using the `volumes` passthrough in `Cross.toml`:

``toml
[build.env]
volumes = ["HOME"]
```

This will automatically mount the home directory and define the `HOME` environment variable inside the container, so it should be able to install required files as desired. However, this will then install on the host filesystem.
