### ISSUE TITLE
`--target=armv7-unknown-linux-musleabihf` crashes without LTO

### ISSUE THREAD

**Issue by fenollp** [cross-rs/cross#416]
Building without link time optimization (`lto = false`) had my program crash (`mmap` complained about unaligned memory).
I wonder if that could be due to the per-crate optimizations done before linking as LTO disables these?

If this is the case maybe there are some optimizations happening before link time that discard musl symbols on the account of static linking? Or something.

Not sure I should report here. I haven't found similar issues on the cargo nor rust repositories.

```
# rustc --version
rustc 1.44.0-nightly (b2e36e6c2 2020-04-22)
# cargo version
cargo 1.44.0-nightly (8751eb301 2020-04-21)
# cross version
cargo 1.44.0-nightly (8751eb301 2020-04-21)
```
cc https://github.com/canselcik/libremarkable/pull/28

**Comment by fenollp** [comment]
Note: any lto value but `false` fixes the issue (`true`, `"fat"`, `"thin"`).
And `"thin"` is faster.

**Comment by Alexhuszagh** [comment]
This doesn't seem to be an issue anymore, as the latest builds allow for no LTO with building libremarkable itself or as a dependency. Runing `test.sh` from [cross_issue416](https://github.com/Alexhuszagh/cross_issue416) produces no errors on either the `dev` (`lto = "off"`) or `release` (`lto = "fat"`) profiles, and it seems `libremarkable` no longer needs `lto = true` when compiling for musl.

**Comment by fenollp** [comment]
Well it's been 2 years since I filed this issue and we've changed the mmap crate used by libremarkable since. Your reproducibility attempt does not use the old code. But whatever, thanks for taking a look anyway.

**Comment by Alexhuszagh** [comment]
This is fair, so I've specifically tried with the exact versions you were using previously (or pretty close, some dependencies might have changed and therefore this is inexact, but likely as close as I can to it). On the newest commit [55977ff6276a27b7845b0651117b51d65c7f84c5](https://github.com/Alexhuszagh/cross_issue416/commit/55977ff6276a27b7845b0651117b51d65c7f84c5) I specifically fetch v0.3.2 of libremarkable and v0.4.6 of atomic, and ensure the local versions are used in the project.

I also made a few minor patches to ensure everything compiles on v1.62.0 nightly. As the newest versions of cross don't support Rust v1.44.0 anymore (only v1.50.0+), I used a more recently nightly. Everything works, so I believe this has been fixed in newer images. 

Let me know if there any other issues: I know this is an old issue, but I'd rather bugs like this don't regress. Thank you.
