### ISSUE TITLE
How to detect QEMU user-mode emulation?

### ISSUE THREAD

**Issue by asomers** [cross-rs/cross#429]
QEMU user-mode emulation isn't perfect.  Plenty of tests fail when run in that environment.  For example, ptrace isn't even implemented by qemu, at least not for all architectures.  So I would like to simply skip ptrace-related tests when running under QEMU user-mode emulation.  How can I detect at runtime if that's the case?

**Comment by Alexhuszagh** [comment]
You're not generally supposed to detect if you're running as a Qemu user (although there's many unstable ways of trying to detect this). Probably the best way would just be to check the following:

1. If `CROSS_RUNNER` is defined and set to `qemu-user`, it's qemu. 
2. If `CROSS_RUNNER` is not defined and the target is not i[3-6]86 0r x86_64, then it's qemu.

That's probably the most reliable way, since relying on `CARGO_TARGET_${TARGET}_RUNNER` could also be `node` or `wine`, or a native runner for x86 Linux images.

**Comment by asomers** [comment]
Oh, here's what I eventually came up with.  The only time my project is executed in QEMU is during CI.  So I just add `RUSTFLAGS=--cfg qemu` on the tasks that use qemu.  Then I disable those tests at compile time.
