### ISSUE TITLE
s390x toolchain generates binaries for GLIBC 2.18 which is incompatible with RHEL 7

### ISSUE THREAD

**Issue by ancwrd1** [cross-rs/cross#451]
In the zLinux world the Red Hat Interprise Linux 7 is a very common distro. Unfortunately it comes with GLIBC 2.17 so the binaries created with the cross tool cannot be run due to some missing symbols.

**Comment by Hoverbear** [comment]
Seems similar to #455

**Comment by Alexhuszagh** [comment]
This might be an issue for a few reasons:

1. Need to change package management for `s390x-unknown-linux-gnu` to CentOS 7.
2. There are no provided packages for `glibc-s390x-linux-gnu` in any official repository, and `gcc-c++-s390x-linux-gnu` only exists (without the shared libraries) in EPEL.

This means compiling glibc from source, which means we'd probably be better off using [crosstool-ng](https://github.com/crosstool-ng/crosstool-ng) entirely, which is quite a lot of work. It's definitely not impossible, and I'll add a section to the wiki about how to use older toolchain versions, but I don't think we can support this out-of-the-box: it's too much new code, a new dependency, and too much maintenance long term.

**Comment by Alexhuszagh** [comment]
Uh, this is relatively more complex than desired, because there's a lot of bugs in `crosstool-ng` due to a lack of maintenance, and would require essentially all the patches I've made for my C++ analog of `cross`. Simply put, unless there's a lot of demand, it's probably not worth documenting since it requires a lot of effort and debugging.

**Comment by Alexhuszagh** [comment]
Update: we're going to be using `crosstool-ng` anyway to fix other issues (see #426), so although we won't support it, I can get some sample files showing how to build this with ct-ng 1.24.0. This will allow you to create a custom docker image with minimal work for this purpose, which will be documented on the wiki.

**Comment by ancwrd1** [comment]
Thanks for the feedback. With docker and cargo cross it's certainly easier; we are currently using a custom crosstool-ng toolchain for s390x which implies some additional setup with cargo config, environment variables, etc.

**Comment by Alexhuszagh** [comment]
Sounds perfect, I'll document it in the wiki and create my own repository with config and Dockerfiles for these, so others can plug-and-play to use them. It'd slow down our CI by a lot, and also it's a lot of maintenance for so many builds long term, but I think it's a good idea since most of our infra is already done here.
