### ISSUE TITLE
Support target `aarch64-apple-darwin` on 64-bit x86 macOS

### ISSUE THREAD

**Issue by rossmacarthur** [cross-rs/cross#508]

**Comment by DarrienG** [comment]
Perhaps this could be supported on the M1 MacBooks as well too!

**Comment by Alexhuszagh** [comment]
This won't be done in cross proper since we cannot ship pre-built images with the macOS SDK, however, we have Dockerfiles that only require a tarball for the macOS SDK in [cross-toolchains](https://github.com/cross-rs/cross-toolchains). We're currently waiting on a resubmitted [PR](https://github.com/cross-rs/cross-toolchains/pull/8) to support `aarch64-apple-darwin`.

**Comment by Alexhuszagh** [comment]
https://github.com/cross-rs/cross-toolchains/pull/11 has been merged, so this is now supported. You will have to provide your own macOS SDK.
