### ISSUE TITLE
Tips to speed up compilation

### ISSUE THREAD

**Issue by jiayihu** [cross-rs/cross#509]
Is there anything that can be done to speed up the cross-compilation? A native compilation taking about 1min can easily become 20mins within Docker. I usually go playing a blitz 5min+3s chess game meanwhile 😄

I'm currently using Docker Desktop on MacOS and I have a 15" MBP 2018. I've allocated 6 CPUs, 4GB RAM and 1GB Swap to Docker.

**Comment by jiayihu** [comment]
I have tried to add `cached` and `delegated` as suggested in https://github.com/rust-embedded/cross/issues/355 and by reading https://github.com/docker/for-mac/issues/77 but it didn't change a bit. A debug recompilation without any file changed takes 24s on MacOS, 3mins with cross.

I guess it's something CPU-bound which can't be improved much

**Comment by ChzenChzen** [comment]
@jiayihu the problem is IO on Mac

**Comment by Alexhuszagh** [comment]
Cached and delegated are no longer supported on macOS Docker (see [here](https://github.com/cross-rs/cross/issues/355#issuecomment-1140483204)). Unfortunately, IO on mac with Docker is quite slow, and this is likely the issue. Using remote docker on an SSH server might work better, which we recently added. Please note you'd have to use persistent data volumes to see any enhancement: otherwise it would be much slower.

We might need to limit the amount copied back, since you might just want the builds and not the incremental artifacts, etc.

**Comment by Alexhuszagh** [comment]
Closed since we now have full [remote Docker support](https://github.com/cross-rs/cross/wiki/Remote), which includes options to only copy changed files when using persistent data volumes. This might in some cases be much faster than running Docker locally on macOS, and if not, there's very little we can do. We can't use Podman right now (see #756, #757), and lima/nerdctl is very much so in beta, so this is outside the scope of cross.

**Comment by abcd-ca** [comment]
@Alexhuszagh would you mind sharing a brief note about why the need for remote docker and what kind of computer would be suitable to get? I have a pretty fast M1 Mac, not clear why it’s slow. Is a remote Intel PC with Ubuntu on the same LAN what is being suggested as a build server?

**Comment by Emilgardis** [comment]
On the Mac M1 the docker images can be slow to run due to bad QEMU virtualization. using CROSS_REMOTE with the context being the local host would not solve the issue.

You might have better milage using an aarch64 native image (which we don't host right now, see https://github.com/cross-rs/cross/issues/751#issuecomment-1193206945 for an example)

**Comment by Alexhuszagh** [comment]
We're hoping soon to deploy native ARM64 images soon, the major obstacle currently is requiring self-hosted runners. However, I'll be re-integrating some automated testing for the process.

**Comment by abcd-ca** [comment]
Happy to test, thanks!
