### ISSUE TITLE
error: couldn't create a temp dir: Permission denied (os error 13) at path "/tmp/rustc0EYM3K"

### ISSUE THREAD

**Issue by rivertam** [cross-rs/cross#515]
This started happening suddenly. I don't remember any changes with my docker setup, Rust setup, Cargo setup, or anything else.

Compiling my project suddenly fails with a permission error:

```
   Compiling bots v0.5.0 (/project/bots)
     Running `rustc --crate-name full-command-redacted`
error: couldn't create a temp dir: Permission denied (os error 13) at path "/tmp/rustc0EYM3K"
```

cross version:

```
└─[$] <git:(rivertam/quick-renames*)> cross --version                                         
cross 0.2.1
cargo 1.45.0 (744bd1fbb 2020-06-15)
```

**Comment by Alexhuszagh** [comment]
This is unlikely to be related to cross: did you previously run Docker as root and then as a normal user? Check the permissions of `"/tmp/rustc0EYM3K"` using `ls -la "/tmp/rustc0EYM3K"`.

**Comment by Alexhuszagh** [comment]
That's unusual, since creating temporary directories should be fine for a normal user. Can you post the output with `--verbose` when running, if possible, and if you're using rootless Docker or the container engine? It's quite possible `--user 1000:1000` might cause it so you can no longer write to the mounted filesystem (due to a lack of permissions) if using rootless docker.

**Comment by rivertam** [comment]
Yeah, I bet it was a problem with Docker. Maybe something with BuildKit. Don't bother -- thanks for the response.
