### ISSUE TITLE
Minify impact of CHANGELOG.md enforcement

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#662]
Currently, if a PR adds a CHANGELOG.md entry and the base is updated with another entry, the PR will have a merge conflict.

We should somehow solve this, either by not requiring changelog entries (and automatically generating them when needed), or some other way.

**Comment by tombruijn** [comment]
I'm a big fan of using [changesets](https://github.com/atlassian/changesets/), small files in a `.changeset` directory that get merged into the CHANGELOG.md file before release. Because they're all different files there will be no conflicts.
The tool I linked is not required, there are other ways to automate it if necessary. It's just Markdown files, even the YAML frontmatter is not required if you don't want to automatically bump version numbers.
Here's a small example that hopefully helps visualize it for a Ruby gem release https://github.com/appsignal/appsignal-ruby/commit/353811731b5f3af13efe597471b3dce7a6bacfb8 using our [own publishing tool](https://github.com/appsignal/mono/). Note the changeset file being removed and merged into the CHANGELOG.md file.

**Comment by Alexhuszagh** [comment]
We could technically use git-cliff as well but I don't love this solution since it differs substantially from our changelog policies:
1. It parses existing commits, which we don't enforce PRs to have a single commit.
2. It's commit-based and not issue or PR-based: it seems to be able to changes without writing commits, but if so, it doesn't have any annotation whatsoever.
