### ISSUE TITLE
How to port docker images to debian ? #armhf need 5.10 kernel

### ISSUE THREAD

**Issue by nikhilavrio** [cross-rs/cross#677]
Ubuntu does not maintain linux-images in 20.04 for armhf

However Debian maintains them.

Should we port the docker images for armhf from Ubuntu 16.04 to latest Debian having Kernel Versio n 5.10 ?

**Comment by Alexhuszagh** [comment]
We shouldn't need to since we install from a toolchain provided by ARM itself. See [arm-unknown-linux-gnueabihf.sh](https://github.com/Alexhuszagh/cross/blob/2bafc9defa782ca9b628659cea09033170fbcaa9/docker/arm-unknown-linux-gnueabihf.sh) in the pending PR to update the image versions (#591). All of the ARM hard-float images besides `arm-unknown-linux-musleabihf` use Ubuntu 20.04, which uses `18.04`. I forget the reason why I use an older image version there, it might just be oversight.

**Comment by Alexhuszagh** [comment]
I'll get an example up and running on how to use Debian images to add more packages and add them to the FAQ. I don't think we should port the images to Debian, as this would be a breaking change.

**Comment by Alexhuszagh** [comment]
I've added examples of install Debian packages when extending a container. See [Using Debian Repositories](https://github.com/cross-rs/cross/wiki/FAQ#using-debian-repositories) on the wiki.
