### ISSUE TITLE
Make FreeBSD builds more resiliant

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#695]
FreeBSD frequently breaks our images, removing older resources.

We need a way to select a range of versions to not constantly have to patch them.

**Comment by Emilgardis** [comment]
Is there some kind of authoritative file provided for us query the latest versions from?

**Comment by Alexhuszagh** [comment]
We could always use the archive, or we could query using FTP and a regex to find the latest version:

For example, in [FreeBSD-Archive i386](http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/i386/), we have all older versions of 12 from 12.0-12.2.

For querying the latest release, we could always use curl:

```bash
max_freebsd_12() {
    local best=
    local minor=0
    local m=
    for release in $@; do
        m=$(echo "$release" | cut -d '.' -f 2 | cut -d '-' -f 1)
        if [ "$m" -gt "$minor" ]; then
            best="$release"
            minor="$m"
        fi
    done
    if [[ -z "$best" ]]; then
        echo "Could not find best release for FreeBSD 12." 1>&2
        exit 1
    fi
    echo "$best"
}

releases=($(curl --silent --list-only ftp.freebsd.org/pub/FreeBSD/releases/i386/ | grep RELEASE))
latest=$(max_freebsd_12 ${releases[@]})
```

This would break if FreeBSD 12 is no longer supported, however.

**Comment by Alexhuszagh** [comment]
A maintainer of FreeBSD has also suggested this [URL](https://people.freebsd.org/~jmg/FreeBSD-snap/snapshot.idx.xz), which we can decompress to find the latest, authoritative versions. Each line is off the following:

```text
iso 12.3-RELEASE amd64 bootonly xxx unspec xxx FreeBSD-12.3-RELEASE-amd64-bootonly.iso https://download.freebsd.org/ftp/releases/ISO-IMAGES/12.3/FreeBSD-12.3-RELEASE-amd64-bootonly.iso 20211207210319.1F6683569@freefall.freebsd.org
...
iso 12.3-RELEASE i386 bootonly xxx unspec xxx FreeBSD-12.3-RELEASE-i386-bootonly.iso https://download.freebsd.org/ftp/releases/ISO-IMAGES/12.3/FreeBSD-12.3-RELEASE-i386-bootonly.iso 20211207210319.1F6683569@freefall.freebsd.org
```

We could download the file, grep for our architecture and `iso 12.*-RELEASE`, and then find the newest version as a result. I'm currently working on `freebsd-extras.sh`, since this is breaking right now. There's a better way to get the package list using `packagesite.txz`, decompressing it, parsing it, and then getting our values for `openssl` and `sqlite3`.

**Comment by Alexhuszagh** [comment]
Parsing the `openssl` and `sqlite3` versions works quite robustly when parsing `packagesite.yaml`, which can be parsed by `jq` since `jq` handles multiple JSON documents in a single file:

```bash
$ openssl_version=$(jq -c '. | select ( .name == "openssl" ) | .version' packagesite.yaml)
$ sqlite3_version=$(jq -c '. | select ( .name == "sqlite3" ) | .version' packagesite.yaml)
$ echo "$openssl_version" "$sqlite3_version"
"1.1.1o,1" "3.37.2,1"
```

This fixes an issue in [freebsd-extras.sh](https://github.com/cross-rs/cross/blob/f77cf8fac72f0d7a81f8686a28e53404c6c65ba6/docker/freebsd-extras.sh#L10) where the correct version now is now `1.1.1o,1`, not `1.1.1n,1`. This should be very resilient.
