### ISSUE TITLE
cross --list lists commands that will not run

### ISSUE THREAD

**Issue by abentley** [cross-rs/cross#715]
```
$ cross --list|grep -C1 deb
    d                    alias: doc
    deb
    doc                  Build a package's documentation
$ cross deb
error: no such subcommand: `deb`

	Did you mean `b`?
```
"deb" here is [cargo-deb](https://github.com/kornelski/cargo-debl).  It would be nice if it could be used to generate deb packages for old distros, but since it can't, it shouldn't be listed.

**Comment by Alexhuszagh** [comment]
There seems to be 2 issues here, I believe.

This seems to be an issue with `deb` being recognized as a sucommand explicitly, but `cargo-deb` is not actually installed for the image's cargo. Normally, for a list of recognized subcommands, we run them in the image, otherwise, we fall back to cargo on the host. However, this doesn't work since we don't necessarily have the correct toolchain on the host.

Related Issues/PRS:
#130 
#210 

The other issue is that `cross --list` actually falls back to the host cargo, so it lists every subcommand on the host, which I don't believe is desirable. We should probably add `--list` to the known subcommands.

An extra feature worth considering is due to custom images, it might be worth writing a config file with extra subcommands that are written at the end of the build step, so that these subcommands are run using cross and the rest fall back to cargo. We could also just parse the output of `cargo --list` in the image and determine if the subcommand is installed on the image's cargo. This would be especially relevant if pre-build hooks (#635) or similar are ever added.
