### ISSUE TITLE
error: linker `i686-w64-mingw32-gcc` not found

### ISSUE THREAD

**Issue by brandonros** [cross-rs/cross#758]
```
 $ CROSS_CONTAINER_ENGINE=docker cross build --target i686-pc-windows-gnu
   Compiling vpi v0.0.1 (/Users/brandonros/Desktop/dpdu-http/vpi)
   Compiling remoter v0.0.1 (/Users/brandonros/Desktop/dpdu-http/remoter)
error: linker `i686-w64-mingw32-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `vpi` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `remoter` due to previous error

Brandons-MacBook-Air:dpdu-http brandonros 2022-06-06 13:25:44 $ uname -a
Darwin Brandons-MacBook-Air.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
```

It feels like it isn't running in Docker?

**Comment by Alexhuszagh** [comment]
Can you provide the output the cross version? Are you installing from git? The latest cross versions will also warn you if you fall back to the host.

**Comment by Alexhuszagh** [comment]
> ```
> $ cross --version
> cross 0.2.1
> cargo 1.61.0 (a028ae42f 2022-04-29)
> ```

Yeah that means you're using the very old version installed from crates.io, which has some major bugs we're fixing in a new release. For a while, we had a lack of maintainers, so we've been patching some errors that had built up over time. If you reinstall cross from git (as shown above), this should fix your issue. You can always use a specific commit if you'd like to lock version dependencies. For example, to use the currently latest commit, and ensure you've audited the correct version, use:

```bash
cargo install --git https://github.com/cross-rs/cross --rev 6a7fa09d6307acb5380475b134ff749c7cd9ed35
```

Thanks for your patience with the lack of recent releases, due to the lack of maintainers.
