### ISSUE TITLE
Support lima

### ISSUE THREAD

**Issue by messense** [cross-rs/cross#888]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

https://github.com/lima-vm/lima

Linux virtual machines, typically on macOS, for running containerd.

It can be used as a replacement of Docker Desktop for Mac.

### Describe why this would be a good inclusion for `cross`

`lima nerdctl` is mostly compatible with `docker`, so it can be used to replace `docker` cli.

The benefits for end user is that [`Lima is free software (Apache License 2.0), while Docker for Mac is not`](https://github.com/lima-vm/lima#advantages-compared-to-docker-for-mac).

**Comment by Alexhuszagh** [comment]
Do you know if Lima runs rootless or not? We probably also need to detect rootless Docker as well, on a separate note. It seems like there might not be much work as long as the `nerdctl.lima` wrapper is used.

**Comment by messense** [comment]
The default template runs rootless I think.

https://github.com/lima-vm/lima/blob/a250961e868c372a20ee4170f69d63e39359a51a/examples/default.yaml#L145

**Comment by Alexhuszagh** [comment]
This might be an issue (see same for #756). I'm currently running on a x86_64 Linux host, so I'll have to test on macOS at well but I'm not very optimistic.

### Attempts

**Native Lima**

```bash
$ limactl start default
$ nerdctl.lima run -it --rm -v "$PWD":/project:Z -w /project ubuntu:20.04 bash                           
WARN[0006] unsupported volume option "Z" 
$ touch a
touch: cannot touch 'a': Read-only file system
```

**Podman Emulation**

```bash
$ limactl start --name=podman template://podman
$ podman system connection add lima "unix:///home/ahuszagh/.lima/podman/sock/podman.sock"
$ podman system connection default lima
$ podman --remote run quay.io/podman/hello   # this works
# works, using local podman. needs SELinux label for r/w functionality
$ podman run -it --rm -v "$PWD":/project:Z -w /project ubuntu:20.04 bash
# fails, and is read-only without the SELinux label
$ podman --remote run -it --rm -v "$PWD":/project:Z -w /project ubuntu:20.04 bash
Error: error preparing container a9f3dc4e9aee5f85f584f30605f2012f991460ce9644a46d253e52676846cdd8 for attach: lsetxattr /home/ahuszagh/Downloads/.Rhistory: read-only file system
```

**Docker Emulation**

```bash
$ limactl start --name=docker template://docker
$ docker context create lima --docker "host=unix:///home/ahuszagh/.lima/docker/sock/docker.sock"
$ docker context use lima
$ docker run hello-world   # this works
$ $ docker run -it --rm -v "$PWD":/project:Z -w /project ubuntu:20.04 bash
$ touch a
touch: cannot touch 'a': Read-only file system
```

### SELinux

I use Fedora with SELinux by default, so maybe this was an issue with an enforcing policy? So I tried a permissive policy:

```bash
$ getenforce 
Enforcing
$ sudo setenforce 0
$ nerdctl.lima run -it --rm -v "$PWD":/project:Z -w /project ubuntu:20.04 bash
WARN[0000] unsupported volume option "Z"                
$ touch a
touch: cannot touch 'a': Read-only file system
```

And unfortunately, that still doesn't work. Even using the raw shell doesn't work:

```bash
$ lima
$ touch a
touch: cannot touch 'a': Read-only file system
```

### Summary

This might be possible with changing the filesystem overlays, but that should probably be the default, rather than the norm.

**Comment by messense** [comment]
https://github.com/lima-vm/lima/blob/a250961e868c372a20ee4170f69d63e39359a51a/examples/default.yaml#L50-L53

The default template mounts home directory in read-only mode by default.

**Comment by Alexhuszagh** [comment]
I'm pretty sure this works out-of-the-box if that's enabled, which isn't exactly a great sign however. We need to home directory for the cargo cache/registry I believe. We currently only mount the toolchain in `/rust` as read-only, so everything else should or needs to be writeable. I think it's well-beyond the scope of cross to manually edit config files, so I guess the only patch would be `--userns host`, and it works out-of-the-box if that's removed.

Maybe we could add a command-line flag warning if `lima` is being used, and remove `--userns host` if it is? We could probably also add an environment variable `CROSS_USER_NAMESPACE`, and if it's not provided, default to the desired option (`host` for everything besides lima, a specific value otherwise, or if empty or `none`, then don't provide it`.

**Comment by Alexhuszagh** [comment]
#891 has preliminary support for this, which is mostly just removing the `--userns` flag, which can be overridden manually by the user. We'll probably keep it as a custom container engine, since there's a lot of issues with lima that make it difficult to support out-of-the-box (we can't edit a running instance, the defaults prevent out-of-the-box use, and it doesn't support some important flags we use normally).

I think just making it so the features required to use lima are available is good enough?

**Comment by messense** [comment]
> I think just making it so the features required to use lima are available is good enough?

Yes! It's better than nothing.

**Comment by Alexhuszagh** [comment]
Once that's done, I can document it on the wiki. I'll add it to my TODO list, but feel free to ping me if it's not mentioned.

**Comment by Alexhuszagh** [comment]
This now works on macOS (and Linux earlier), but there's 1 major caveat: since `/tmp/lima` is the default writeable directory, but this is mapped to `/private/tmp/lima` when canonicalizing, Lima does not know where to find this directory (unlike Docker). Running this outside of the tmp directory works, however. I'll file an upstream issue.

**Comment by Alexhuszagh** [comment]
I've since added documentation on using [Lima](https://github.com/cross-rs/cross/wiki/FAQ#using-lima-nerdctl) to the wiki, as well as [macOS](https://github.com/cross-rs/cross/wiki/FAQ#macos-host)-specific issues. When these issues are resolved in Lima, or bind mounts allow writable access by default, I'll update the wiki as needed.

**Comment by Alexhuszagh** [comment]
We've added partial, improved support for Lima in build steps via https://github.com/cross-rs/cross/pull/1033#event-7497087196, so it will work well using custom images. Since the install step for Lima is quite long during CI, this may break from commit to commit.
