### ISSUE TITLE
`sccache` not found for `i686-unknown-linux-gnu`

### ISSUE THREAD

**Issue by Laura7089** [cross-rs/cross#914]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

It looks like the docker image for `i686-unknown-linux-gnu` doesn't have `sccache` installed.

### What target(s) are you cross-compiling for?

i586-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2

### Example

```
warpgate on  main via 🦀 v1.63.0-nightly
❯ cross build --target i686-unknown-linux-gnu
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `/usr/bin/sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (never executed)

Caused by:
  No such file or directory (os error 2)
```

```
warpgate on  main via 🦀 v1.63.0-nightly
❯ docker run --rm -it ghcr.io/cross-rs/i686-unknown-linux-gnu:0.2.2
root@4c39b8698519:/# sccache
bash: sccache: command not found
```

**Comment by Alexhuszagh** [comment]
It doesn't, we have recipes for how to use [sccache](https://github.com/cross-rs/cross/wiki/Recipes#sccache) with cross, but it's not installed by default. Note that this can be done even easier with pre-build hooks now, so you don't have to maintain images. This is for a few reasons: 1 is we're allowing native images for not just `x86_64-unknown-linux-gnu` soon, so this would require building from source for each, and using sccache isn't widely used enough and we have to limit what's included in each image.

But, we do make it easy to integrate it in. Here's a working project using [pre-build hooks](https://github.com/cross-rs/wiki_assets/tree/main/Recipes/sccache). If you want the example code here, see below:

**Cross.toml**

```toml
[target.i686-unknown-linux-gnu]
dockerfile = "Dockerfile.sccache-i686"

[build.env]
passthrough = [
    "SCCACHE_ERROR_LOG",
    "SCCACHE_LOG",
    "SCCACHE_AZURE_CONNECTION_STRING",
    "SCCACHE_AZURE_BLOB_CONTAINER",
    "SCCACHE_DIR",
]
```

**Dockerfile.sccache-i686**

```Dockerfile
FROM ghcr.io/cross-rs/${target}:main
ARG DEBIAN_FRONTEND=noninteractive

COPY sccache.sh /
RUN /sccache.sh x86_64-unknown-linux-musl

ENV RUSTC_WRAPPER="/usr/bin/sccache"
```

**sccache.sh**

```bash
#!/bin/bash

set -x
set -euo pipefail

# shellcheck disable=SC1091
. lib.sh

main() {
    local triple
    local tag
    local td
    local url="https://github.com/mozilla/sccache"
    triple="${1}"

    install_packages unzip tar

    # Download our package, then install our binary.
    td="$(mktemp -d)"
    pushd "${td}"
    tag=$(git ls-remote --tags --refs --exit-code \
        "${url}" \
        | cut -d/ -f3 \
        | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
        | sort --version-sort \
        | tail -n1)
    curl -LSfs "${url}/releases/download/${tag}/sccache-${tag}-${triple}.tar.gz" \
        -o sccache.tar.gz
    tar -xvf sccache.tar.gz
    rm sccache.tar.gz
    cp "sccache-${tag}-${triple}/sccache" "/usr/bin/sccache"
    chmod +x "/usr/bin/sccache"

    # clean up our install
    purge_packages
    popd
    rm -rf "${td}"
    rm "${0}"
}

main "${@}"
```

The last one will have to change if you want to build from source rather than use a pre-built binary.

**Comment by Laura7089** [comment]
Thanks for all the info! That worked a dream.
